### ISSUE TITLE
Checkpoint 1 ready to review

### ISSUE THREAD

**Issue by jvjohnson1** [mad-java-ent-f21/NoFlyTravelPlanner#1]
@pawaitemadisoncollege Checkpoint 1 is ready to review
Learned: Nothing new here, because checkpoint 1 is about documentation and planning.  What is important is to have a realistic scope and a clear purpose, and I think I've got that.
Challenge: Finding a realistic scope that meets all requirements.  At the same time, developing a pattern for something that will be a positive part of a portfolio. 
Blockers: No good tool for creating a wireframe - my student access to Figma had expired.  I made designs I could build from using plain old Word, but that didn't come out neat.

**Comment by pawaitemadisoncollege** [comment]
@jvjohnson1 

- [x] Missing readme.md at the root of your repository. This is like the home page of your repository and the first thing people see when viewing your repo in Github. It should include your problem statement, solution and list of technologies used.
- [x] Missing project plan.
- [x] Missing time log.
- [x] Missing user stories.
- [x] Missing screen design.
- [x] Missing .gitignore file.

Please be sure all of the items above are visible in GitHub at either the root of your project or in a "design" folder at the root before "resubmitting". Thanks!

**Comment by jvjohnson1** [comment]
@pawaitemadisoncollege I hope I got it right this time!

Everything was pushed when I submitted, but it was in the wrong folder.  My fault.

**Comment by pawaitemadisoncollege** [comment]
@jvjohnson1 A good start here! Problem statement does a good job explaining the purpose of the project.

- [x] Time log should include actual hours worked in addition to the tasks completed. 
- [x] Screen design is missing some user stories: log in, search and search results, post travel story. If I overlooked these, please let me know!
- [x] Regarding the project plan - I'd recommending determining which web service/api you will consume prior to week 11 - that may be a bit late in the game.

**Comment by jvjohnson1** [comment]
I hope this ties up the loose ends on this one.  It feels good to be catching  up instead of falling farther behind, but I've still got a time crunch.
