### ISSUE TITLE
Individual Project - Design/Code Review 1

### ISSUE THREAD

**Issue by spartan7777** [mad-java-ent-f21/NoFlyTravelPlanner#3]
# Design/Code Review 1
​
## Project: No Fly Travel Planner
​
### Developer: Julie Johnson
​
### Reviewer: Tosan Ogedengbe
​
|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. EVERY item should have *at least* one "kudos" and one suggestion for improvement|
|**Problem Statement**|1. Accurately describes the project's purpose.<br> 2. Is professional and free of typos, slang, etc.<br> 3. Thoroughly explains the problem and the solution.<br> 4. Is understandable by the average person.|The problem statement is very thorough and does a great job of explaining the purpose of the application and how the app intends to carry out its mission. You have a very interesting and practical idea which seems like it will be a lot of fun to make this come to life. The problem statement was very professional, and it is easily understandable by the average person. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens. |The application's description and the user stories generated from that description seem to flow very well. There were some visual sketches provided to describe design and layout. The sketches (by designer admission) were very plain and not really intended to be shown, so the lack of detail was understandable. That said, it would have been nice to see more detailed designs so that they, along with the problem statement could really help drive home the workflow of this app. There was a main page design, (with much of the HTML and CSS being complete) but that was also a rough idea that would be further modified for this application. Still, all the designs presented were good to see. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model. <br> 2. There are at least two 1-to-many relationships.<br> 3. The model represents good database design. <br>|The database was in place, but things were not working correctly at review time. |
|**Code**|1. Proper Maven project structure is used. <br> 2. a .gitignore file for IntelliJ Java projects has been implemented. <br> 3. There is not any redundant or copy/paste code in the JSPs or classes.<br> 4. Classes are appropriately-sized (no monster classes).<br> Property files are used appropriately: no hard-coded values. <br> 5. Logging statements are used rather than System.out.println and printStackTrace (be sure to use a search to look for these!).<br> 6. There are appropriate unit tests/code coverage. <br>|Maven structure was there and looked good. There was a lot of code already in place and it all looked clean. There was basic code for the application's main entities, with the more main code for them to be added later. There was also a DAO that was annotated with hibernate, and a TestDAO as well. Not all the entities were here, but it was mentioned that these are on the way. While everything was not here, I did not see any issues with what was presented. |

**Comment by pawaitemadisoncollege** [comment]
@spartan7777 @jvjohnson1 Overall a good review. One thing to be sure to check for when reviewing are those sneaky printlns. The search feature in GitHub is a nice way to find these:
![Screen Shot 2021-10-11 at 6 01 23 PM](https://user-images.githubusercontent.com/13874466/136865175-85750ba2-d1b8-4bcc-9f61-9cefe8d9670b.png)

**Comment by jvjohnson1** [comment]
Good review.  Thanks

**Comment by pawaitemadisoncollege** [comment]
I think this https://github.com/mad-java-ent-f21/NoFlyTravelPlanner/blob/9e015e9b63b07b441472d58f18afc8bb5482df02/src/test/java/com/jvjohnson1/no_fly/persistence/Database.java#L57-L58 is still an issue. In fact, it looks like an endless loop... The code in the method calls itself?!
